### ISSUE TITLE
Runtime Exception on Demo\build: Unhandled flag: emitUseStrict

### ISSUE THREAD

**Issue by rohit1406** [Ziriax/SkiaWasmDemo#1]
Hello Sir,

Thanks for spending time on creating this repo.
I was struggling to get the Skia build for WASM but could not achieve it using the official guidelines provided on skia website. Your repository helping me to build the cpp and run on browser. I have successfully build the skia library. While building the Demo\build, I am getting below error. Can you please help me what could be the cause of this and how can I resolve it?

building:ERROR: Closure compiler run failed:

building:ERROR: <ref *1> Error: java.lang.RuntimeException: Unhandled flag: emitUseStrict
    at bS.AP [as Og] (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:9322:25772)
    at bS.DP [as Qg] (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:9322:25967)
    at bS.yP (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:2975:48)
    at bS.GP (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:1047:19)
    at new bS (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:1049:19)
    at YSd (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:9180:132)
    at sS (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:2442:29)
    at vS (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:3940:44)
    at /root/emsdk/upstream/emscripten/node_modules/google-closure-compiler-js/jscomp.js:4181:46
    at CompilerJS.run (/root/emsdk/upstream/emscripten/node_modules/google-closure-compiler/lib/node/closure-compiler-js.js:54:17)
    at /root/emsdk/upstream/emscripten/node_modules/google-closure-compiler/cli.js:164:31 {
  '__java$exception': {
    g: null,
    e: 'Unhandled flag: emitUseStrict',
    backingJsObject: [Circular *1]
  }
}

em++: error: closure compiler failed (rc: 1): /root/emsdk/node/14.18.2_64bit/bin/node --max_old_space_size=8192 /root/emsdk/upstream/emscripten/node_modules/.bin/google-closure-compiler --compilation_level ADVANCED_OPTIMIZATIONS --language_in ECMASCRIPT_2018 --language_out NO_TRANSPILE --emit_use_strict=false --externs /root/emsdk/upstream/emscripten/src/closure-externs/closure-externs.js --externs /root/emsdk/upstream/emscripten/src/closure-externs/node-externs.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/tls.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/string_decoder.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/https.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/assert.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/url.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/vm.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/domain.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/events.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/path.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/readline.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/child_process.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/net.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/fs.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/tty.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/core.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/zlib.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/process.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/cluster.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/repl.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/querystring.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/os.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/punycode.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/http.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/dgram.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/buffer.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/util.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/stream.js --externs /root/emsdk/upstream/emscripten/third_party/closure-compiler/node-externs/dns.js --externs /root/emsdk/upstream/emscripten/src/closure-externs/v8-externs.js --externs /root/emsdk/upstream/emscripten/src/closure-externs/spidermonkey-externs.js --js_output_file /tmp/emscripten_temp_22ikabzc/index.wasm.o.js.cc.js --formatting PRETTY_PRINT --js /tmp/emscripten_temp_22ikabzc/index.wasm.o.js
:-( failure!

Regards,
Rohit

**Comment by ziriax** [comment]
This code is very old. I would first upgrade it if I was you. I'll give it a shot myself

**Comment by ziriax** [comment]
It seems these days Google provides their own docker image for building canvaskit, but I'm unable to get access to grc.io, not sure how that works.

This is their dockerfile

https://github.com/google/skia/blob/main/docker/skia-wasm-release/Dockerfile

**Comment by ShinGeonUi** [comment]
pardon, then... is it over??? i really need your help please! how can i see that you made it except the .js. i have big question of your way. how could you do interface between "html's canvas_id" with "wasm".

**Comment by rohit1406** [comment]
hi ShinGeonUi and Ziriax, I did try with the repository from Ziriax and it worked for me when I do the below change:

In Demo/compile.sh, remove "--closure 1" from RELEASE_CONF variable.

This change worked for me.

Regards,
Rohit

**Comment by ShinGeonUi** [comment]
Thank you. you are my role model

2022년 4월 1일 (금) 오전 12:05, Rohit Shamrao Muneshwar ***@***.***>님이
작성:

**Comment by ziriax** [comment]
@rohit1406 could you provide a PR? 🙂

**Comment by rohit1406** [comment]
Hi Ziriax, yes sure :)
